spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebank
    username: root
    password: distinct
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: bank-accounts
server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


